services:
  cloudlearningtracker-db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: cloudlearningtracker-db
      ports:
        - "1433:1433"
      environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
        MSSQL_PID: "Developer"
      volumes:
        - db-data:/var/opt/mssql
      restart: unless-stopped
      networks: 
        - backend

  cloudlearningtracker-api:
      image: 455303857199.dkr.ecr.ap-south-1.amazonaws.com/cloudlearningtracker/cloudlearningtracker-api:${API_IMAGE_TAG}
      container_name: cloudlearningtracker-api
      ports:
        - "5168:8080"
      environment:
        ASPNETCORE_URLS: "http://+:8080"
        Jwt__Key: ${Jwt__Key}
        Cors__AllowedOrigins__0: "http://localhost:4200"
        ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      depends_on:
        - cloudlearningtracker-db
      networks: 
        - frontend
        - backend

  cloudlearningtracker-ui:
      image: 455303857199.dkr.ecr.ap-south-1.amazonaws.com/cloudlearningtracker/cloudlearningtracker-ui:${UI_IMAGE_TAG}
      container_name: cloudlearningtracker-ui
      ports:
        - "4200:80"
      depends_on:
        - cloudlearningtracker-api
      networks: 
        - frontend

volumes:
    db-data:

networks:
  frontend:    
  backend:
  
