server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        # If not using ALB pass the API ec2 private ip
        proxy_pass http://10.1.2.16:5168;
        # if using ALB pass DNS name of that ALB
        proxy_pass internal-cloudlearningtracker-api-alb-2068096325.ap-south-1.elb.amazonaws.com

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}