name: Deploy CloudLearningTracker.API

on:
  push:
    branches:
      - main
    paths:
      - 'CloudLearningTracker.API/**'
      - '.github/workflows/api-deploy.yml'

  workflow_dispatch:

jobs:
  build:
    name: Build API Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    outputs:
      image_tag: ${{ steps.image-tag.outputs.image_tag }}
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::455303857199:role/GitHubActions-ECR-Push-Role
            aws-region: ap-south-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Generate Image Tag
          id: image-tag
          run: |
            echo "image_tag=v${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

        - name: Build UI Image
          run: |
            docker build -t cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }} ./CloudLearningTracker.API
            docker tag cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }} 455303857199.dkr.ecr.ap-south-1.amazonaws.com/cloudlearningtracker/cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }}
            docker push 455303857199.dkr.ecr.ap-south-1.amazonaws.com/cloudlearningtracker/cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }}

        - name: List Docker Images
          run: docker images

  deploy:
      name: Deploy API
      runs-on: ubuntu-latest
      needs: build

      permissions:
       id-token: write
       contents: read

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              role-to-assume: arn:aws:iam::455303857199:role/GitHubActions-ECR-Push-Role
              aws-region: ap-south-1

        - name: Read docker compose
          id: compose
          run: |
              # Encode the file to base64 so it fits on a single line safely
              ENCODED_CONTENT=$(base64 -w 0 deployment/api/docker-compose-api.yml)
              echo "content=$ENCODED_CONTENT" >> "$GITHUB_OUTPUT"

        - name: Deploy to Private EC2 using SSM
          run: |
            # 1. Create the deployment script file
            cat << 'EOF' > ssm-script.sh
            # Create deployment folder and set correct ownership
            mkdir -p /home/ec2-user/CloudLearningTracker
            chown -R ec2-user:ec2-user /home/ec2-user/CloudLearningTracker
            cd /home/ec2-user/CloudLearningTracker

            # Decode the base64 string directly into your file
            echo "${{ steps.compose.outputs.content }}" | base64 -d > docker-compose-api.yml

            # Write the .env file with secrets
            cat << 'INNER_EOF' > .env
            API_IMAGE_TAG=${{ needs.build.outputs.image_tag }}
            MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}
            ConnectionStrings__DefaultConnection=${{ secrets.ConnectionStrings__DefaultConnection }}
            Jwt__Key=${{ secrets.Jwt__Key }}
            Cors__AllowedOrigins=${{ secrets.Cors__AllowedOrigins}}
            INNER_EOF

            # Keep file permissions clean for the ec2-user
            chown ec2-user:ec2-user docker-compose-api.yml .env
            chmod 600 .env

            # Run docker actions as ec2-user to avoid root-owned configuration locks
            sudo -u ec2-user bash << 'DEPLOY_EOF'
            cd /home/ec2-user/CloudLearningTracker

            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 455303857199.dkr.ecr.ap-south-1.amazonaws.com

            # Pull new images and restart the stack
            docker compose -f /home/ec2-user/CloudLearningTracker/docker-compose-api.yml pull
            docker compose -f /home/ec2-user/CloudLearningTracker/docker-compose-api.yml up -d --remove-orphans

            DEPLOY_EOF
            EOF

            # 2. Convert script to a safe JSON payload using jq
            jq -n --rawfile cmd ssm-script.sh '{commands: [$cmd]}' > ssm-parameters.json

            # 3. Send command to AWS
            aws ssm send-command \
              --document-name "AWS-RunShellScript" \
              --instance-ids "${{ secrets.API_INSTANCE_ID }}" \
              --parameters file://ssm-parameters.json

