name: Deploy CloudLearningTracker.API

on:
  push:
    branches:
      - main
    paths:
      - 'CloudLearningTracker.API/**'
      - '.github/workflows/api-deploy.yml'

  workflow_dispatch:

jobs:
  build:
    name: Build API Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    outputs:
      image_tag: ${{ steps.image-tag.outputs.image_tag }}
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::455303857199:role/GitHubActions-ECR-Push-Role
            aws-region: ap-south-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Generate Image Tag
          id: image-tag
          run: |
            echo "image_tag=v${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

        - name: Build UI Image
          run: |
            docker build -t cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }} ./CloudLearningTracker.API
            docker tag cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }} 455303857199.dkr.ecr.ap-south-1.amazonaws.com/cloudlearningtracker/cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }}
            docker push 455303857199.dkr.ecr.ap-south-1.amazonaws.com/cloudlearningtracker/cloudlearningtracker-api:${{ steps.image-tag.outputs.image_tag }}

        - name: List Docker Images
          run: docker images

  deploy:
      name: Deploy API
      runs-on: ubuntu-latest
      needs: build
      
      permissions:
       id-token: write
       contents: read

      steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::455303857199:role/GitHubActions-ECR-Push-Role
            aws-region: ap-south-1

      - name: Read docker compose
        id: compose
        run: |
            echo "content<<EOF" >> "$GITHUB_OUTPUT"
            cat deployment/api/docker-compose-api.yml >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Deploy to Private EC2 using SSM
        run: |
          aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "${{ secrets.API_INSTANCE_ID }}" \
            --parameters commands='[
              "mkdir -p /home/ec2-user/CloudLearningTracker",
              "cd /home/ec2-user/CloudLearningTracker",
              "cat > docker-compose-api.yml <<'\''EOF'\'' 
              ${{ steps.compose.outputs.content }}
              EOF",
              "cat > .env <<'\''EOF'\'' 
              API_IMAGE_TAG=${{ needs.build.outputs.image_tag }}
              MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}
              ConnectionStrings__DefaultConnection=${{ secrets.ConnectionStrings__DefaultConnection }}
              Jwt__Key=${{ secrets.JWT_KEY }}
              Cors__AllowedOrigins=${{ secrets.Cors__AllowedOrigins}}
              EOF",
              "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 455303857199.dkr.ecr.ap-south-1.amazonaws.com",
              "docker compose -f docker-compose-api.yml pull",
              "docker compose -f docker-compose-api.yml up -d"
            ]'